# Generated by Django 5.2.4 on 2025-08-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='headlin',
            new_name='headline',
        ),
    ]
